<a href="https://colab.research.google.com/github/udaykondreddy/Code-for-learn-machinelearning/blob/master/AutoML/lazy_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Check the detailed explanation of this code here

In [34]:
!wget -O "learn_ml_2021_grand_ai_challenge-dataset.zip" "https://dockship-job-models.s3.ap-south-1.amazonaws.com/6828f10e6390a3be901c3246ba58f4fd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIDOPTEUZ2LEOQEGQ%2F20210111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210111T110924Z&X-Amz-Expires=1800&X-Amz-Signature=d068b842427e17943a0d9f3a8946edce32b1c28eccec8c19d33d504cecedf5d1&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22learn_ml_2021_grand_ai_challenge-dataset.zip%22"

--2021-01-11 11:34:08--  https://dockship-job-models.s3.ap-south-1.amazonaws.com/6828f10e6390a3be901c3246ba58f4fd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIDOPTEUZ2LEOQEGQ%2F20210111%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210111T110924Z&X-Amz-Expires=1800&X-Amz-Signature=d068b842427e17943a0d9f3a8946edce32b1c28eccec8c19d33d504cecedf5d1&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22learn_ml_2021_grand_ai_challenge-dataset.zip%22
Resolving dockship-job-models.s3.ap-south-1.amazonaws.com (dockship-job-models.s3.ap-south-1.amazonaws.com)... 52.219.64.87
Connecting to dockship-job-models.s3.ap-south-1.amazonaws.com (dockship-job-models.s3.ap-south-1.amazonaws.com)|52.219.64.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50544 (49K) [binary/octet-stream]
Saving to: ‘learn_ml_2021_grand_ai_challenge-dataset.zip’

learn_ml_2021_grand 100%[===================>]  49.36K   226KB/s    in 0.2s

2021-01-11 11:34:09 (226 KB/s) - ‘learn_ml_2021_grand_ai_challenge-dataset.zip’ saved [50544/50544]

In [35]:
!unzip  /content/learn_ml_2021_grand_ai_challenge-dataset.zip -d .

Archive:  /content/learn_ml_2021_grand_ai_challenge-dataset.zip
replace ./new_sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ./new_sample_submission.csv
replace ./new_test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ./new_test.csv
replace ./new_train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: ./new_train.csv

In [36]:
import pandas as pd

In [37]:
tData = pd.read_csv("/content/new_train.csv")

In [38]:
tData.head()

         Date  Open-Stock-1  ...  Volume-Stock-5  Turnover-Stock-5
0  2010-06-01       1889.70  ...         1786082   213845404410000
1  2010-06-02       1848.00  ...         1307410   155564994855000
2  2010-06-03       1864.10  ...         1482919   182640434320000
3  2010-06-04       1906.00  ...         1454459   181767075850000
4  2010-06-07       1867.00  ...         1424594   172272511430000

[5 rows x 36 columns]

In [39]:
def getStock(df, number):
  '''
    Returns features and labels for each stock
  '''

  features = df[['Open-Stock-'+str(number), 'High-Stock-'+str(number), 'Low-Stock-'+str(number), 'VWAP-Stock-'+str(number)]]
  try:
    label = df['Close-Stock-'+str(number)]
    return features, label
  except:
    return features

In [40]:
stock1Feats, stock1Label = getStock(tData, 1)
stock2Feats, stock2Label = getStock(tData, 2)
stock3Feats, stock3Label = getStock(tData, 3)
stock4Feats, stock4Label = getStock(tData, 4)
stock5Feats, stock5Label = getStock(tData, 5)

In [41]:
training_set = stock1Feats.iloc[:280, :]
test_set = stock1Feats.iloc[280:, :]

training_set_y = stock1Label.iloc[:280]
test_set_y = stock1Label.iloc[280:]

In [42]:
df_train_norm = training_set.copy()
df_test_norm = test_set.copy()

In [43]:
!pip install lazypredict

Requirement already satisfied: lazypredict in /usr/local/lib/python3.6/dist-packages (0.2.7)
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.6/dist-packages (from lazypredict) (7.1.2)

In [45]:
from lazypredict.Supervised import LazyClassifier, LazyRegressor
from sklearn.model_selection import train_test_split
from sklearn import datasets

##Regression

In [46]:
# fit all models
reg = LazyRegressor(predictions=True)
models, predictions = reg.fit(df_train_norm, df_test_norm, training_set_y, test_set_y)

100%|██████████| 39/39 [00:01<00:00, 19.76it/s]

[11:37:42] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

In [47]:
models

                               R-Squared    RMSE  Time Taken
Model
HuberRegressor                      1.00    4.09        0.03
SGDRegressor                        1.00    4.35        0.05
LassoCV                             1.00    4.47        0.09
RANSACRegressor                     1.00    4.49        0.01
RidgeCV                             1.00    4.63        0.01
Ridge                               1.00    4.66        0.01
BayesianRidge                       1.00    4.87        0.01
Lars                                1.00    4.96        0.02
TransformedTargetRegressor          1.00    4.96        0.01
LarsCV                              1.00    4.96        0.04
LassoLarsCV                         1.00    4.96        0.02
LinearRegression                    1.00    4.96        0.01
OrthogonalMatchingPursuitCV         1.00    4.96        0.02
LassoLarsIC                         1.00    5.21        0.01
OrthogonalMatchingPursuit           1.00    5.76        0.02
Lasso                               1.00    8.42        0.02
PassiveAggressiveRegressor          1.00   29.19        0.01
ElasticNetCV                        0.99   70.11        0.06
LassoLars                           0.96  159.12        0.01
ElasticNet                          0.95  185.40        0.01
GaussianProcessRegressor            0.68  463.41        0.02
LinearSVR                          -0.61 1046.37        0.01
MLPRegressor                       -0.77 1097.36        0.64
DecisionTreeRegressor              -1.13 1203.80        0.01
ExtraTreeRegressor                 -1.13 1203.87        0.01
ExtraTreesRegressor                -1.14 1205.06        0.12
BaggingRegressor                   -1.15 1208.38        0.02
RandomForestRegressor              -1.15 1209.24        0.20
XGBRegressor                       -1.16 1211.10        0.04
GradientBoostingRegressor          -1.16 1211.36        0.08
KNeighborsRegressor                -1.17 1215.02        0.01
AdaBoostRegressor                  -1.22 1228.07        0.08
HistGradientBoostingRegressor      -1.32 1255.07        0.13
LGBMRegressor                      -1.32 1256.64        0.04
NuSVR                              -2.48 1537.39        0.04
DummyRegressor                     -2.49 1541.65        0.01
SVR                                -2.51 1545.82        0.02
KernelRidge                        -6.28 2224.46        0.02

In [48]:
predictions

    AdaBoostRegressor  BaggingRegressor  ...  XGBRegressor  LGBMRegressor
0             2536.18           2559.65  ...       2557.21        2488.31
1             2536.18           2547.74  ...       2557.21        2488.31
2             2487.67           2499.57  ...       2496.87        2488.31
3             2517.89           2503.26  ...       2514.57        2488.31
4             1880.37           1858.19  ...       1861.26        1912.37
5             1880.37           1858.19  ...       1861.26        1912.37
6             1880.37           1858.19  ...       1861.26        1912.37
7             1880.37           1858.19  ...       1861.26        1912.37
8             1880.37           1858.19  ...       1861.26        1912.37
9             1880.37           1858.19  ...       1861.26        1912.37
10            1880.37           1858.19  ...       1861.26        1912.37
11            1880.37           1858.19  ...       1861.26        1912.37
12            1880.37           1858.19  ...       1861.26        1912.37
13            1880.37           1858.19  ...       1861.26        1912.37
14            1880.37           1858.19  ...       1861.26        1912.37
15            1880.37           1858.19  ...       1861.26        1912.37
16            1880.37           1858.19  ...       1861.26        1912.37
17            1880.37           1858.19  ...       1861.26        1912.37
18            1880.37           1858.19  ...       1861.26        1912.37

[19 rows x 38 columns]

##Classification

In [49]:
from sklearn.datasets import load_iris

In [50]:
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.2,random_state =0)
classifier = LazyClassifier(predictions=True)
models,predictions = classifier.fit(X_train, X_test, y_train, y_test)

100%|██████████| 30/30 [00:00<00:00, 43.04it/s]

In [51]:
models

                               Accuracy  ...  Time Taken
Model                                    ...
LGBMClassifier                     1.00  ...        0.03
BaggingClassifier                  1.00  ...        0.02
XGBClassifier                      1.00  ...        0.03
SVC                                1.00  ...        0.01
SGDClassifier                      1.00  ...        0.01
DecisionTreeClassifier             1.00  ...        0.01
RandomForestClassifier             1.00  ...        0.14
QuadraticDiscriminantAnalysis      1.00  ...        0.01
ExtraTreesClassifier               1.00  ...        0.11
Perceptron                         1.00  ...        0.01
KNeighborsClassifier               1.00  ...        0.01
NuSVC                              1.00  ...        0.01
LogisticRegression                 1.00  ...        0.02
LinearDiscriminantAnalysis         1.00  ...        0.01
AdaBoostClassifier                 0.97  ...        0.09
LabelSpreading                     0.97  ...        0.01
LabelPropagation                   0.97  ...        0.01
GaussianNB                         0.97  ...        0.01
ExtraTreeClassifier                0.97  ...        0.01
LinearSVC                          0.97  ...        0.01
RidgeClassifier                    0.80  ...        0.01
RidgeClassifierCV                  0.80  ...        0.01
CalibratedClassifierCV             0.80  ...        0.04
PassiveAggressiveClassifier        0.87  ...        0.01
NearestCentroid                    0.80  ...        0.01
BernoulliNB                        0.63  ...        0.01
DummyClassifier                    0.30  ...        0.01
CheckingClassifier                 0.37  ...        0.01

[28 rows x 5 columns]

In [52]:
predictions

    AdaBoostClassifier  BaggingClassifier  ...  XGBClassifier  LGBMClassifier
0                    2                  2  ...              2               2
1                    1                  1  ...              1               1
2                    0                  0  ...              0               0
3                    2                  2  ...              2               2
4                    0                  0  ...              0               0
5                    2                  2  ...              2               2
6                    0                  0  ...              0               0
7                    1                  1  ...              1               1
8                    1                  1  ...              1               1
9                    1                  1  ...              1               1
10                   1                  2  ...              2               2
11                   1                  1  ...              1               1
12                   1                  1  ...              1               1
13                   1                  1  ...              1               1
14                   1                  1  ...              1               1
15                   0                  0  ...              0               0
16                   1                  1  ...              1               1
17                   1                  1  ...              1               1
18                   0                  0  ...              0               0
19                   0                  0  ...              0               0
20                   2                  2  ...              2               2
21                   1                  1  ...              1               1
22                   0                  0  ...              0               0
23                   0                  0  ...              0               0
24                   2                  2  ...              2               2
25                   0                  0  ...              0               0
26                   0                  0  ...              0               0
27                   1                  1  ...              1               1
28                   1                  1  ...              1               1
29                   0                  0  ...              0               0

[30 rows x 28 columns]

Link to the [project](https://github.com/shankarpandala/lazypredict)